=== jakartaee/platform-tck/internal/docs/dtd/javadoc_assertions.dtd
<!-- 
Javadoc Assertion DTD file. This DTD is used to describe assertions taken from javadoc.
-->
<!-- Version 0.2 -->
<!-- By Stephen DiMilla -->
<!-- Last Modification: -->
<!ELEMENT javadoc (next-available-id, previous-id, technology, id, name, version, assertions?)>
<!ELEMENT next-available-id (#PCDATA)>
<!ELEMENT previous-id (#PCDATA)>
<!ELEMENT technology (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT assertions (assertion+)>
<!ELEMENT assertion (modified?, id, description, keywords?, package, class-interface, (method | field), comment?, depends?)>
<!ATTLIST assertion
	required (true | false) #REQUIRED
	impl-spec (true | false) #REQUIRED
	status (active | deprecated | removed) #REQUIRED
	testable (true | false) #REQUIRED
        priority (low | medium | high) #IMPLIED
>
<!ELEMENT modified EMPTY>
<!ELEMENT keywords (keyword+)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT package (#PCDATA)>
<!ELEMENT class-interface (#PCDATA)>
<!ELEMENT method (parameters?, throw?)>
<!ATTLIST method
	name CDATA #REQUIRED
	return-type CDATA #REQUIRED
>
<!ELEMENT field EMPTY>
<!ATTLIST field
	name CDATA #REQUIRED
	type CDATA #REQUIRED
>
<!ELEMENT throw (#PCDATA)>
<!ELEMENT depends (depend+)>
<!ELEMENT depend (#PCDATA)>
<!ELEMENT parameters (parameter+)>
<!ELEMENT parameter (#PCDATA)>
<!--



Example Assertion:


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE javadoc SYSTEM "http://busgo1208.us.oracle.com/CTS/XMLassertions/dtd/javadoc_assertions.dtd">
<?xml-stylesheet type="text/xsl" href="http://busgo1208.us.oracle.com/CTS/XMLassertions/xsl/javadoc_assertions.xsl"?>
<javadoc>
	<next-available-id>205</next-available-id>
	<previous-id>100</previous-id>
	<technology>JAXRPC</technology>
	<id>JAX-RPC 1.0</id>
	<name>Java API for XML-based RPC</name>
	<version>0.7</version>
	<assertions>
		<assertion required="true" impl-spec="false" status="active" testable="true">
			<id>7</id>
			<description/>
			<package>javax.xml.rpc</package>
			<class-interface>ServiceFactory</class-interface>
			<method-field>newInstance</method-field>
			<type-returns>javax.xml.rpc.ServiceFactory</type-returns>
			<throws>
				<throw>javax.xml.rpc.ServiceException</throw>
			</throws>
		</assertion>
		<assertion required="true" impl-spec="false" status="active" testable="true">
			<id>8</id>
			<description>
                            Create a Service instance.
                        </description>
			<package>javax.xml.rpc</package>
			<class-interface>ServiceFactory</class-interface>
			<method-field>createService</method-field>
			<type-returns>javax.xml.rpc.Service</type-returns>
			<parameters>
				<parameter>java.net.URL</parameter>
				<parameter>javax.xml.rpc.namespace.QName</parameter>
			</parameters>
		</assertion>
		<assertion required="true" impl-spec="false" status="active" testable="true">
			<id>9</id>
			<description>If any error in creation of the                      specified service</description>
			<package>javax.xml.rpc</package>
			<class-interface>ServiceFactory</class-interface>
			<method-field>createService</method-field>
			<type-returns>javax.xml.rpc.Service</type-returns>
			<parameters>
				<parameter>java.net.URL</parameter>
				<parameter>javax.xml.rpc.namespace.QName</parameter>
			</parameters>
			<throws>
				<throw>javax.xml.rpc.ServiceException</throw>
			</throws>
		</assertion>
		<assertion required="true" impl-spec="false" status="active" testable="true">
			<id>10</id>
			<description>
                            Create a Service instance.
                        </description>
			<package>javax.xml.rpc</package>
			<class-interface>ServiceFactory</class-interface>
			<method-field>createService</method-field>
			<type-returns>javax.xml.rpc.Service</type-returns>
			<parameters>
				<parameter>javax.xml.rpc.namespace.QName</parameter>
			</parameters>
		</assertion>
	</assertions>
</javadoc>

-->

=== jakartaee/platform-tck/internal/docs/jaxm/JAXMJavadocAssertions.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE javadoc SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/javadoc_assertions.dtd">
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<javadoc>
<next-available-id>35</next-available-id>
<previous-id>1</previous-id>
<technology>JAXM</technology>
<id>JAXM 1.1</id>
<name>Java API for XML Messaging</name>
<version>Final Draft</version>
<assertions>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:1</id>
<description>
                            Constructs a new &lt;code&gt;URLEndpoint&lt;/code&gt; object using the given URL.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>URLEndpoint</class-interface>
<method name="URLEndpoint" return-type="URLEndpoint">
<parameters>
<parameter>java.lang.String</parameter>
</parameters>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:2</id>
<description>
                            Gets the URL associated with this &lt;code&gt;URLEndpoint&lt;/code&gt; object.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>URLEndpoint</class-interface>
<method name="getURL" return-type="java.lang.String"/>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:3</id>
<description/>
<package>javax.xml.messaging</package>
<class-interface>ProviderConnectionFactory</class-interface>
<method name="ProviderConnectionFactory" return-type="ProviderConnectionFactory"/>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:4</id>
<description>
                            Creates a &lt;code&gt;ProviderConnection&lt;/code&gt; object to the messaging provider that  is associated with this &lt;code&gt;ProviderConnectionFactory&lt;/code&gt;  object.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>ProviderConnectionFactory</class-interface>
<method name="createConnection" return-type="javax.xml.messaging.ProviderConnection"/>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:5</id>
<description>if there is an error in creating the             connection</description>
<package>javax.xml.messaging</package>
<class-interface>ProviderConnectionFactory</class-interface>
<method name="createConnection" return-type="javax.xml.messaging.ProviderConnection">
<throw>javax.xml.messaging.JAXMException</throw>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:6</id>
<description>
                            Creates a default &lt;code&gt;ProviderConnectionFactory&lt;/code&gt; object.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>ProviderConnectionFactory</class-interface>
<method name="newInstance" return-type="javax.xml.messaging.ProviderConnectionFactory"/>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:7</id>
<description>if there was an error creating the             default &lt;code&gt;ProviderConnectionFactory&lt;/code&gt;</description>
<package>javax.xml.messaging</package>
<class-interface>ProviderConnectionFactory</class-interface>
<method name="newInstance" return-type="javax.xml.messaging.ProviderConnectionFactory">
<throw>javax.xml.messaging.JAXMException</throw>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:8</id>
<description/>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="JAXMServlet" return-type="JAXMServlet"/>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:9</id>
<description>
                            Initializes this &lt;code&gt;JAXMServlet&lt;/code&gt; object using the given   &lt;code&gt;ServletConfig&lt;/code&gt; object and initializing the  &lt;code&gt;msgFactory&lt;/code&gt; field with a default  &lt;code&gt;MessageFactory&lt;/code&gt; object.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="init" return-type="void">
<parameters>
<parameter>ServletConfig</parameter>
</parameters>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:10</id>
<description/>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="init" return-type="void">
<parameters>
<parameter>ServletConfig</parameter>
</parameters>
<throw>ServletException</throw>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:11</id>
<description>
                            Sets this &lt;code&gt;JAXMServlet&lt;/code&gt; object's &lt;code&gt;msgFactory&lt;/code&gt;  field with the given &lt;code&gt;MessageFactory&lt;/code&gt; object.
                              A &lt;code&gt;MessageFactory&lt;/code&gt; object for a particular profile needs to  be set before a message is received in order for the message to be   successfully internalized.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="setMessageFactory" return-type="void">
<parameters>
<parameter>javax.xml.soap.MessageFactory</parameter>
</parameters>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:12</id>
<description>
                            Internalizes the given &lt;code&gt;HttpServletRequest&lt;/code&gt; object  and writes the reply to the given &lt;code&gt;HttpServletResponse&lt;/code&gt;  object.
                              &lt;P&gt;  Note that the value for the &lt;code&gt;msgFactory&lt;/code&gt; field will be used to  internalize the message. This ensures that the message  factory for the correct profile is used.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="doPost" return-type="void">
<parameters>
<parameter>HttpServletRequest</parameter>
<parameter>HttpServletResponse</parameter>
</parameters>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:13</id>
<description>if there is a servlet error</description>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="doPost" return-type="void">
<parameters>
<parameter>HttpServletRequest</parameter>
<parameter>HttpServletResponse</parameter>
</parameters>
<throw>ServletException</throw>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:14</id>
<description>if there is an input or output error</description>
<package>javax.xml.messaging</package>
<class-interface>JAXMServlet</class-interface>
<method name="doPost" return-type="void">
<parameters>
<parameter>HttpServletRequest</parameter>
<parameter>HttpServletResponse</parameter>
</parameters>
<throw>java.io.IOException</throw>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:15</id>
<description>
                            Constructs a &lt;code&gt;JAXMException&lt;/code&gt; object with no  reason or embedded &lt;code&gt;Throwable&lt;/code&gt; object.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>JAXMException</class-interface>
<method name="JAXMException" return-type="JAXMException"/>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:16</id>
<description>
                            Constructs a &lt;code&gt;JAXMException&lt;/code&gt; object with the given  &lt;code&gt;String&lt;/code&gt; as the reason for the exception being thrown.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>JAXMException</class-interface>
<method name="JAXMException" return-type="JAXMException">
<parameters>
<parameter>java.lang.String</parameter>
</parameters>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:17</id>
<description>
                            Constructs a &lt;code&gt;JAXMException&lt;/code&gt; object with the given  &lt;code&gt;String&lt;/code&gt; as the reason for the exception being thrown  and the given &lt;code&gt;Throwable&lt;/code&gt; object as an embedded  exception.
                        </description>
<package>javax.xml.messaging</package>
<class-interface>JAXMException</class-interface>
<method name="JAXMException" return-type="JAXMException">
<parameters>
<parameter>java.lang.String</parameter>
<parameter>java.lang.Throwable</parameter>
</parameters>
</method>
</assertion>
<assertion required="true" impl-spec="false" status="active" testable="true">
<id>JAXM:JAVADOC:18</id>
<description>
