=== jakartaee/platform-tck/internal/docs/dtd/spec_assertions.dtd
<!-- 
Spec Assertion DTD file. This DTD is used to describe assertions taken from specs .
-->
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->
<!-- Version 0.2 -->
<!-- By Stephen DiMilla -->
<!-- Last Modification: -->
<!--
The spec element describes all the elements used to uniquely identify the specification where the assertions originated from.
 -->
<!ELEMENT spec (next-available-id, previous-id, technology, id, name, version, location-names, assertions?)>
<!--
The next-available-id element identifies the next id that should be used when creating new assertions.
-->
<!ELEMENT next-available-id (#PCDATA)>
<!--
The previous-id element identifies the previous id that was used when creating new assertions.
-->
<!ELEMENT previous-id (#PCDATA)>
<!--
The technology element contains the name of the technology that the assertions pertain to.
-->
<!ELEMENT technology (#PCDATA)>
<!--
The id element specifies the id of the specification or the unique id an assertion can have. The id must be unique in the document. 
-->
<!ELEMENT id (#PCDATA)>
<!--
The name element specifies the name of a spec, chapter or section
-->
<!ELEMENT name (#PCDATA)>
<!--
The version element describes the version the specification
-->
<!ELEMENT version (#PCDATA)>
<!--
The location-names element describes the names of the chapters and sections in the spec
-->
<!ELEMENT location-names (chapters)>

<!ELEMENT chapters (chapter+)>
<!--
The chapter element describes the individual chapter id in the spec
-->
<!ELEMENT chapter (sections?)>
<!ATTLIST chapter
	id CDATA #REQUIRED
	name CDATA #REQUIRED
>

<!ELEMENT sections (section+)>
<!--
The section element describes the individual section id in the spec
-->
<!ELEMENT section EMPTY>
<!ATTLIST section
	id CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!--
The location element describes the chapter and section ids in the spec where the assertion came from. 
-->
<!ELEMENT location EMPTY>
<!ATTLIST location
	chapter CDATA #REQUIRED
	section CDATA #REQUIRED
>
<!--
The description element contains a full description of the assertion in detail.
-->
<!ELEMENT description (#PCDATA)>
<!--
The assertions element describes all the required elements used for expressing a specification assertion using XML.
-->
<!--
The keywords element defines a set of keywords associated with an assertion.  Please note that
there are two keywords that already have specific meaning.  Users must take great care not to use
these reserved keywords for any purpose other than their intended purpose.  The two keywords
that are reserved are "application-role" and "application-server-role".  The "application-role"
keywork denotes that this assertion applies to an application or an application component.  This
type of assertion is most likely verified by the application verification team.  The
"application-server-role" keyword denotes that this assertion applies to an application server.
This type of assertion is most likely verified by the CTS team.  Note that both these keywords
can be specified within the same assertion.  At least one of these keywords will be present
in every assertion.
-->
<!ELEMENT keywords (keyword+)>
<!--
The keyword element describes a keyword associated with the assertion. This tag will be used by a tool to easily find an assertion based on keywords.
-->
<!ELEMENT keyword (#PCDATA)>
<!--
The comment element is used to store any comments about the assertion.
-->
<!ELEMENT comment (#PCDATA)>
<!--
The depends element contains all the dependencies an assertion may have. To be realized, and assertion may need another assertion to
be realize before. The depend element is used to describe that type of scenario. 
-->
<!ELEMENT depends (depend+)>
<!--
The depends' order attribute is used when an assertion must follow more that one assertions before being executed.

Example:
Assertion 3 must always occurs after assertion 1 and assertion 6

<depends order="assertion 1, asssertion 6">
    <depend> assertion 1 </depend>
    <depend> assertion 6 </depend>
</depends>    

-->
<!ATTLIST depends
	order CDATA #IMPLIED
>
<!--
The depend element describes the dependency an assertion can have with another assertion. 
The element's value is always an assertion <id> value.
-->
<!ELEMENT depend (#PCDATA)>
<!-- 
The sub assertions element is used to expand an assertion that contains several elements that are each an assertion
of their own.

For example, see below
-->
<!ELEMENT sub-assertions (assertion+)>

<!ELEMENT assertions (assertion+)>
<!--
The assertion element is an XML-view a specification assertion. 
id: This element must be unique. 
description: This is taken literally from the specification. 
keywords:  can be used to associate a common name across multiple assertions.
chapter: Identifies which chapter the assertion came from.
section: Identifies which section the assertion came from.
depends: Identifies other assertions that must be realized inorder for this assertion to be realized.
sub-assertions: These are assertions that make up/ are a component of  the parent assertion. 

An assertion also have attributes used for describing the actual state of the assertion:
	required: Is the assertion a required element in the specification (true or false)
	impl-spec: Is the assertion an implementation specific element (true or false)
	defined-by: Is the assertion based on a technology requirement or is it a platform requirement
	status  The current status of the assertion 
	testable: Is the the assertion testable from a compatability standpoint.
        priority: What is the priority of the assertion.
	
-->
<!ELEMENT assertion (id, description, keywords?, location, comment?, depends?, sub-assertions?)>
<!ATTLIST assertion
	required (true | false) #REQUIRED
	impl-spec (true | false) #REQUIRED
	defined-by (technology | platform) #REQUIRED
	status (active | deprecated | removed) #REQUIRED
	testable (true | false) #REQUIRED
        priority (low | medium | high) #IMPLIED
>

<!--
Example Assertion:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd">
<?xml-stylesheet type="text/xsl" href="https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/xsl/spec_assertions.xsl"?>
<spec>
	<next-available-id>602</next-available-id>
	<previous-id>599</previous-id>
	<technology>JAXRPC</technology>
	<id>JAXRPC 1.0</id>
	<name>Java API for XML-based RPC</name>
	<version>0.7</version>
	<location-names>
	<chapters>
		<chapter id="3" name="Requirements">
			<sections>
				<section id="R01" name="Protocol Bindings"/>
				<section id="R02" name="Transport"/>
				<section id="R03" name="Supported Type Systems"/>
			</sections>
		</chapter>
		<chapter id="4" name="WSDL/XML to Java Mapping"/>
			<sections>
				<section id="1" name="XML Names"/>
				<section id="2.1" name="Simple Types"/>
				<section id="2.2" name="Array"/>
			</sections>
		<chapter id="14" name="Interoperability">
			<sections>
				<section id="1" name="Interoperability Scenario"/>
				<section id="1" name="Interoperability Scenario"/>
				<section id="3.1" name="SOAP based Interoperability"/>
				<section id="3.2" name="SOAP Encoding and XML Schema Support"/>
				<section id="3.3" name="Transport"/>
				<section id="3.4" name="WSDL Requirements"/>
				<section id="3.5" name="Processing of SOAP Headers"/>
				<section id="3.6" name="Mapping of Remote Exceptions"/>
				<section id="3.7" name="Security"/>
				<section id="3.8" name="Transaction"/>
			</sections>
		</chapter>
		<chapter id="15" name="Extensible Type Mapping">
			<sections>
				<section id="2" name="Type Mapping Framework"/>
				<section id="3.1" name="TypeMappingRegistry"/>
			</sections>
		</chapter>
		<chapter id="18" name="XML Schema Support"/>
	</location-names>
	<assertions>
		<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
			<id>441</id>
			<description>The JAX-RPC specification requires the use of one of the following representations for remote call in a SOAP message</description>
			<location chapter="14" section="3.2"/>
			<sub-assertions>
				<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
					<id>441.1</id>
					<description>Encoded representation using the SOAP 1.1 encoding</description>
					<location chapter="14" section="3.2"/>
					<sub-assertions>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.1.1</id>
							<description>The rules and format of serialization for the XML data types are based on the SOAP 1.1 encoding [4].</description>
							<location chapter="14" section="3.2"/>
						</assertion>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.1.2</id>
							<description>An interoperable JAX-RPC implementation is required to support the SOAP 1.1 encoding.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
						<assertion required="false" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.1.3</id>
							<description>Interoperability requirements for any other encodings are outside the scope of the JAX-RPC specification.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
					</sub-assertions>
				</assertion>
				<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
					<id>441.2</id>
					<description>Literal representation</description>
					<location chapter="14" section="3.2"/>
					<sub-assertions>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.2.1</id>
							<description>Each message part in the SOAP body references a concrete schema definition using the element attribute.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.2.2</id>
							<description>Each message part in the SOAP body references a concrete schema definition using the type attribute.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
					</sub-assertions>
				</assertion>
			</sub-assertions>
		</assertion>
	</assertions>
</spec>
-->

=== jakartaee/platform-tck/internal/docs/jaxws/wsa/wsametadata.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd"[
<!ENTITY wsametadata_ch2 SYSTEM "wsametadata_ch2.xml">
<!ENTITY wsametadata_ch3 SYSTEM "wsametadata_ch3.xml">
<!ENTITY wsametadata_ch4 SYSTEM "wsametadata_ch4.xml">
<!ENTITY wsametadata_ch5 SYSTEM "wsametadata_ch5.xml">
]>

<?xml-stylesheet type="text/xsl" href="https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/xsl/spec_assertions.xsl"?>
<spec>
	<next-available-id>30000</next-available-id>

	<previous-id>29999</previous-id>
	<technology>WSAMetaData</technology>
	<id>WSAMD</id>
	<name>Web Services Addressing 1.0 - MetaData</name>
	<version>1.0</version>
	<location-names>            
		<chapters>
			<chapter id = "1" name = "Introduction">
				<sections>
					<section id = "1" name = "Notation Conventions"/>
					<section id = "2" name = "Namespaces"/>
				</sections>
			</chapter>
			<chapter id = "2" name = "Including WSDL Metadata in EPRs">
				<sections>			
					<section id = "1" name = "Referencing WSDL Metadata from an EPR"/>
					<section id = "2" name = "Embedding WSDL Metadata in an EPR"/>
                                </sections>
			</chapter>	
			<chapter id = "3" name = "Indicating Use of WS-Addressing">
				<sections>			
					<section id = "1" name = "WS-Policy Assertions"/>
					<section id = "1.1" name = "Addressing Assertion"/>
					<section id = "1.2" name = "AnonymousResponses Assertion"/>
					<section id = "1.3" name = "NonAnonymousResponses Assertion"/>
					<section id = "1.4" name = "Examples (Compact Form)"/>
					<section id = "1.5" name = "Examples (Normal Form)"/>
					<section id = "1.6" name = "Finding Compatible Policies"/>
				</sections>                                
			</chapter>	
			<chapter id = "4" name = "Specifying Message Addressing Properties in WSDL">
				<sections>			
					<section id = "1" name = "Extending WSDL Endpoints with an EPR"/>
					<section id = "1.1" name = "WSDL 2.0 Component Model Changes"/>
                                        <section id = "2" name = "Destination"/>
					<section id = "3" name = "Reference Parameters"/>
					<section id = "4" name = "Action"/>
					<section id = "4.1" name = "Explicit Association"/>
                                        <section id = "4.2" name = "Default Action Pattern for WSDL 2.0"/>
                                        <section id = "4.3" name = "WSDL 2.0 Component Model Changes"/>
					<section id = "4.4" name = "Default Action Pattern for WSDL 1.1"/>
				</sections>
			</chapter>
			<chapter id = "5" name = "WS-Addressing and WSDL Message Exchange Patterns">
				<sections>			
					<section id = "1" name = "WSDL 1.1 Message Exchange Patterns"/>
                                        <section id = "1.1" name = "One-way"/>
					<section id = "1.2" name = "Request-Response"/>
                                        <section id = "1.3" name = "Notification"/>
					<section id = "1.4" name = "Solicit-response"/>
					<section id = "2" name = "WSDL 2.0 Message Exchange Patterns"/>
					<section id = "2.1" name = "In-only"/>
					<section id = "2.2" name = "Robust In-only"/>
                                        <section id = "2.3" name = "In-out"/>
					<section id = "2.4" name = "In-optional-out"/>
                                        <section id = "2.5" name = "Out-only"/>
					<section id = "2.6" name = "Robust Out-only"/>
                                        <section id = "2.7" name = "Out-in"/>
					<section id = "2.8" name = "Out-optional-in"/>
				</sections>
			</chapter>			
			<chapter id = "6" name = "Conformance"/>
			<chapter id = "7" name = "References">
				<sections>			
					<section id = "1" name = "Normative"/>
					<section id = "2" name = "Informative"/>
				</sections>			
			</chapter>
		</chapters>
	</location-names>
	<assertions>
         &wsametadata_ch2;
         &wsametadata_ch3;
         &wsametadata_ch4;
         &wsametadata_ch5;         
	</assertions>
</spec>

=== jakartaee/platform-tck/internal/docs/connector/jca_1.7/spec/removed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd">
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<spec>
  <next-available-id>331</next-available-id>
  <previous-id>330</previous-id>
  <technology>Connector</technology>
  <id>Connector</id>
  <name>Java EE Connector API</name>
  <version>1.7</version>
  <location>
    <chapters />
    <chapter id="19" name="API Requirements">
      <sections>
        <section id="1" name="Requirements of the App Server" />
      </sections>
    </chapter>
    <chapter id="17" name="Common Client Interface">
      <sections>
        <section id="6.2" name="InteractionSpec" />
        <section id="10.3" name="ResultSetInfo" />
        <section id="6.1" name="Interaction" />
        <section id="10.1" name="ResultSet Interface" />
        <section id="5.3" name="Connection" />
        <section id="5.1" name="ConnectionFactory" />
        <section id="5.2" name="ConnectionSpec" />
        <section id="7.1" name="ConnectionMetaData" />
        <section id="9.1" name="Component-view Contract" />
        <section id="9.3" name="Resource Adapter-view Contract" />
      </sections>
    </chapter>
    <chapter id="18" name="Metadata Annotations">
      <sections>
        <section id="3" name="Deployment Descriptores and Annotations" />
        <section id="2" name="Goals" />
        <section id="1" name="Overview" />
        <section id="7" name="@Activation" />
        <section id="6" name="@ConnectionDefinition and @ConnectionDefinitions" />
        <section id="5" name="@ConfigProperty" />
        <section id="4" name="@Connector" />
        <section id="8" name="@AdministeredObject" />
      </sections>
    </chapter>
    <chapter id="15" name="Transaction Inflow">
      <sections>
        <section id="4.4" name="Requirements" />
        <section id="4.2" name="Transaction completion processing" />
        <section id="4.6" name="Recommendations" />
      </sections>
    </chapter>
    <chapter id="16" name="Security Inflow">
      <sections>
        <section id="4.1" name="Establishing the Security Context" />
        <section id="4" name="SecurityContext Class" />
        <section id="4.4" name="Security Configuration Responsibilities" />
        <section id="4.5" name="Requirements" />
        <section id="4.2" name="callbacks for Information from the App Server" />
        <section id="4.3" name="Establishing a Principal as the Caller Identity" />
      </sections>
    </chapter>
    <chapter id="13" name="Message Inflow">
      <sections>
        <section id="3" name="Message Inflow Model" />
        <section id="5.6" name="Transacted delivery (using container managed transaction)" />
        <section id="5.4" name="Concurrent delivery of messages" />
        <section id="5.1" name="Sample resource adapter code to illustrate message delivery" />
        <section id="5.9" name="Requirements" />
        <section id="4.5" name="Application Server" />
        <section id="4.9" name="Multiple endpoint activations with similar activation information" />
        <section id="4.7" name="Requirements" />
      </sections>
    </chapter>
    <chapter id="11" name="Generic inflow Context">
      <sections>
        <section id="3" name="Generic Inflow Context Model" />
        <section id="2" name="Goals" />
        <section id="1" name="Overview" />
        <section id="7" name="WorkContextLifecycleListener Interface" />
        <section id="6" name="HintsContext Interface" />
        <section id="5" name="TransactionContext Class" />
        <section id="4" name="WorkContextProvider and WorkContext Interface" />
        <section id="8" name="Illustrative Example" />
      </sections>
    </chapter>
    <chapter id="12" name="Inbound Communication">
      <sections>
        <section id="2" name="An Illustrative Use Case " />
        <section id="1" name="Overview" />
      </sections>
    </chapter>
    <chapter id="3" name="The Connector Architecture">
      <sections>
        <section id="3" name="Requirements" />
        <section id="2" name="Client API" />
        <section id="1" name="System Contracts" />
        <section id="5" name="Standalone Container Environment" />
        <section id="4" name="Non-Managed Environment" />
      </sections>
    </chapter>
    <chapter id="20" name="Packaging Requirements">
      <sections>
        <section id="3" name="Class Loading Requirements" />
        <section id="2" name="Packaging" />
        <section id="1" name="Overview" />
        <section id="7" name="Resource Adapter XML Schema Def" />
        <section id="6" name="JNDI Configuration and Lookup" />
        <section id="4.1" name="ResourceAdapter Provider" />
        <section id="5" name="Interfaces/Classes" />
        <section id="4" name="Deployment" />
        <section id="4.2" name="Deployer" />
      </sections>
    </chapter>
    <chapter id="10" name="Work Management">
      <sections>
        <section id="3" name="Work management Model" />
        <section id="3.2" name="WorkManager Interface " />
        <section id="3.3" name="WorkListener interface and WorkEvent class " />
        <section id="3.5" name="Periodic execution of Work instances " />
      </sections>
    </chapter>
    <chapter id="7" name="Transaction Management">
      <sections>
        <section id="6.2" name="Resource Adapter Requirements" />
        <section id="6.3" name="Transaction Manager Requirements" />
        <section id="13.2" name="Application Server" />
        <section id="3.1" name="Interface: ManagedConnection" />
        <section id="9" name="Connection Sharing" />
        <section id="11" name="Connection Association" />
      </sections>
    </chapter>
    <chapter id="6" name="Connection Management">
      <sections>
        <section id="8.3" name="Connection Event Notifications and Connection Close" />
        <section id="2" name="Goals" />
        <section id="10.1" name="Resource Adapter" />
        <section id="5.3" name="ManagedConnectionFactory" />
        <section id="10.2" name="Application Server" />
        <section id="5.4" name="ManagedConnection" />
        <section id="5.1" name="ConnectionFactory and Connection" />
        <section id="5.2" name="ConnectionManager" />
      </sections>
    </chapter>
    <chapter id="5" name="LifeCycle Management">
      <sections>
        <section id="3.2" name="ManagedConnectionFactory JavaBean and Outbound Communication" />
        <section id="3.1" name="ResourceAdapter JavaBean and bootstraping a resource adapter instance" />
        <section id="3.4" name="ResourceAdapter Shutdown procedure" />
        <section id="3.3" name="ActivationSpec JavaBean and Inbound Communication" />
      </sections>
    </chapter>
    <chapter id="9" name="Security Contract">
      <sections>
        <section id="3" name="Requirements" />
        <section id="2.5" name="ConnectionManager" />
        <section id="2.7" name="ManagedConnection" />
        <section id="2.3" name="GenericCredential" />
        <section id="2.2" name="ResourcePrincipal" />
      </sections>
    </chapter>
  </location>
</spec>

=== jakartaee/platform-tck/internal/docs/jaxws/wsa/wsasoapbinding.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd"[
<!ENTITY wsasoapbinding_ch4 SYSTEM "wsasoapbinding_ch4.xml">
<!ENTITY wsasoapbinding_ch5 SYSTEM "wsasoapbinding_ch5.xml">
<!ENTITY wsasoapbinding_ch6 SYSTEM "wsasoapbinding_ch6.xml">
]>

<?xml-stylesheet type="text/xsl" href="https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/xsl/spec_assertions.xsl"?>
<spec>
	<next-available-id>20000</next-available-id>

	<previous-id>19999</previous-id>
	<technology>WSASOAPBinding</technology>
	<id>WSASB</id>
	<name>Web Services Addressing 1.0 - SOAP Binding</name>
	<version>1.0</version>
	<location-names>
		<chapters>
			<chapter id = "1" name = "Introduction">
				<sections>
					<section id = "1" name = "Notation Conventions"/>
					<section id = "2" name = "Namespaces"/>
				</sections>
			</chapter>
			<chapter id = "2" name = "SOAP 1.2 Addression Feature">
				<sections>			
					<section id = "1" name = "Feature Name"/>
					<section id = "2" name = "Description"/>
					<section id = "3" name = "Properties"/>
					<section id = "4" name = "Interactions with Other SOAP Features"/>
				</sections>
			</chapter>	
			<chapter id = "3" name = "SOAP 1.2 Addressing 1.0 Module">
				<sections>			
					<section id = "1" name = "Module Name"/>
					<section id = "2" name = "Description"/>
					<section id = "2.1" name = "Sending Messages"/>
					<section id = "2.2" name = "Receiving Messages"/>
					<section id = "3" name = "Additional Infoset Items"/>
					<section id = "4" name = "Binding Message Addressing Properties"/>
					<section id = "5" name = "Relationship between SOAP Headers and transport-level properties"/>
				</sections>
			</chapter>	
			<chapter id = "4" name = "SOAP 1.1 Addressing 1.0 Extension">
				<sections>			
					<section id = "1" name = "Extension Name"/>
					<section id = "2" name = "Description"/>
				</sections>
			</chapter>
			<chapter id = "5" name = "Addresses in SOAP">
				<sections>			
					<section id = "1" name = "Use of Anonymous Address in SOAP Response Endpoints"/>
					<section id = "1.1" name = "SOAP 1.1/HTTP"/>
					<section id = "1.2" name = "SOAP 1.2"/>
					<section id = "2" name = "Use of Non-Anonymous Address in SOAP Response Endpoints"/>
					<section id = "2.1" name = "SOAP 1.1/HTTP"/>
					<section id = "2.2" name = "SOAP 1.2"/>
				</sections>
			</chapter>
			<chapter id = "6" name = "Faults">
				<sections>			
					<section id = "1" name = "SOAP 1.2 Fault Binding"/>
					<section id = "2" name = "SOAP 1.1 Fault Binding"/>
					<section id = "3" name = "Fault Detail Elements"/>
					<section id = "3.1" name = "Problem Header QName"/>
					<section id = "3.2" name = "Problem IRI"/>
					<section id = "3.3" name = "Problem Action"/>
					<section id = "3.4" name = "Retry After"/>
					<section id = "4" name = "Predefined Faults"/>
					<section id = "4.1" name = "Invalid Addressing Header"/>
					<section id = "4.1.1" name = "wsa:InvalidAddress"/>
					<section id = "4.1.2" name = "wsa:InvalidEPR"/>
					<section id = "4.1.3" name = "wsa:InvalidCardinality"/>
					<section id = "4.1.4" name = "wsa:MissingAddressInEPR"/>
					<section id = "4.1.5" name = "wsa:DuplicateMessageID"/>
					<section id = "4.1.6" name = "wsa:ActionMismatch"/>
					<section id = "4.1.7" name = "wsa:OnlyAnonymousAddressSupported"/>
					<section id = "4.1.8" name = "wsa:OnlyNonAnonymousAddressSupported"/>
					<section id = "4.2" name = "Message Addressing Header Required"/>
					<section id = "4.3" name = "Destination Unreachable"/>
					<section id = "4.4" name = "Action Not Supported"/>
					<section id = "4.5" name = "Endpoint Unavailable"/>
				</sections>
			</chapter>
			<chapter id = "7" name = "Security Considerations">
				<sections>			
					<section id = "1" name = "Establishing EPR Trust"/>
					<section id = "2" name = "Additional Security Considerations"/>
					<section id = "3" name = "Additional Considerations for SOAP Intermediaries"/>
				</sections>			
			</chapter>
			<chapter id = "8" name = "Conformance">
			</chapter>
			<chapter id = "9" name = "References">
				<sections>			
					<section id = "1" name = "Normative References"/>
					<section id = "2" name = "Other References"/>
				</sections>			
			</chapter>
		</chapters>
	</location-names>
	<assertions>
         &wsasoapbinding_ch4;
         &wsasoapbinding_ch5;
         &wsasoapbinding_ch6;
	</assertions>
</spec>
