=== jakartaee/platform-tck/internal/docs/dtd/spec_assertions.dtd
<!-- 
Spec Assertion DTD file. This DTD is used to describe assertions taken from specs .
-->
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->
<!-- Version 0.2 -->
<!-- By Stephen DiMilla -->
<!-- Last Modification: -->
<!--
The spec element describes all the elements used to uniquely identify the specification where the assertions originated from.
 -->
<!ELEMENT spec (next-available-id, previous-id, technology, id, name, version, location-names, assertions?)>
<!--
The next-available-id element identifies the next id that should be used when creating new assertions.
-->
<!ELEMENT next-available-id (#PCDATA)>
<!--
The previous-id element identifies the previous id that was used when creating new assertions.
-->
<!ELEMENT previous-id (#PCDATA)>
<!--
The technology element contains the name of the technology that the assertions pertain to.
-->
<!ELEMENT technology (#PCDATA)>
<!--
The id element specifies the id of the specification or the unique id an assertion can have. The id must be unique in the document. 
-->
<!ELEMENT id (#PCDATA)>
<!--
The name element specifies the name of a spec, chapter or section
-->
<!ELEMENT name (#PCDATA)>
<!--
The version element describes the version the specification
-->
<!ELEMENT version (#PCDATA)>
<!--
The location-names element describes the names of the chapters and sections in the spec
-->
<!ELEMENT location-names (chapters)>

<!ELEMENT chapters (chapter+)>
<!--
The chapter element describes the individual chapter id in the spec
-->
<!ELEMENT chapter (sections?)>
<!ATTLIST chapter
	id CDATA #REQUIRED
	name CDATA #REQUIRED
>

<!ELEMENT sections (section+)>
<!--
The section element describes the individual section id in the spec
-->
<!ELEMENT section EMPTY>
<!ATTLIST section
	id CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!--
The location element describes the chapter and section ids in the spec where the assertion came from. 
-->
<!ELEMENT location EMPTY>
<!ATTLIST location
	chapter CDATA #REQUIRED
	section CDATA #REQUIRED
>
<!--
The description element contains a full description of the assertion in detail.
-->
<!ELEMENT description (#PCDATA)>
<!--
The assertions element describes all the required elements used for expressing a specification assertion using XML.
-->
<!--
The keywords element defines a set of keywords associated with an assertion.  Please note that
there are two keywords that already have specific meaning.  Users must take great care not to use
these reserved keywords for any purpose other than their intended purpose.  The two keywords
that are reserved are "application-role" and "application-server-role".  The "application-role"
keywork denotes that this assertion applies to an application or an application component.  This
type of assertion is most likely verified by the application verification team.  The
"application-server-role" keyword denotes that this assertion applies to an application server.
This type of assertion is most likely verified by the CTS team.  Note that both these keywords
can be specified within the same assertion.  At least one of these keywords will be present
in every assertion.
-->
<!ELEMENT keywords (keyword+)>
<!--
The keyword element describes a keyword associated with the assertion. This tag will be used by a tool to easily find an assertion based on keywords.
-->
<!ELEMENT keyword (#PCDATA)>
<!--
The comment element is used to store any comments about the assertion.
-->
<!ELEMENT comment (#PCDATA)>
<!--
The depends element contains all the dependencies an assertion may have. To be realized, and assertion may need another assertion to
be realize before. The depend element is used to describe that type of scenario. 
-->
<!ELEMENT depends (depend+)>
<!--
The depends' order attribute is used when an assertion must follow more that one assertions before being executed.

Example:
Assertion 3 must always occurs after assertion 1 and assertion 6

<depends order="assertion 1, asssertion 6">
    <depend> assertion 1 </depend>
    <depend> assertion 6 </depend>
</depends>    

-->
<!ATTLIST depends
	order CDATA #IMPLIED
>
<!--
The depend element describes the dependency an assertion can have with another assertion. 
The element's value is always an assertion <id> value.
-->
<!ELEMENT depend (#PCDATA)>
<!-- 
The sub assertions element is used to expand an assertion that contains several elements that are each an assertion
of their own.

For example, see below
-->
<!ELEMENT sub-assertions (assertion+)>

<!ELEMENT assertions (assertion+)>
<!--
The assertion element is an XML-view a specification assertion. 
id: This element must be unique. 
description: This is taken literally from the specification. 
keywords:  can be used to associate a common name across multiple assertions.
chapter: Identifies which chapter the assertion came from.
section: Identifies which section the assertion came from.
depends: Identifies other assertions that must be realized inorder for this assertion to be realized.
sub-assertions: These are assertions that make up/ are a component of  the parent assertion. 

An assertion also have attributes used for describing the actual state of the assertion:
	required: Is the assertion a required element in the specification (true or false)
	impl-spec: Is the assertion an implementation specific element (true or false)
	defined-by: Is the assertion based on a technology requirement or is it a platform requirement
	status  The current status of the assertion 
	testable: Is the the assertion testable from a compatability standpoint.
        priority: What is the priority of the assertion.
	
-->
<!ELEMENT assertion (id, description, keywords?, location, comment?, depends?, sub-assertions?)>
<!ATTLIST assertion
	required (true | false) #REQUIRED
	impl-spec (true | false) #REQUIRED
	defined-by (technology | platform) #REQUIRED
	status (active | deprecated | removed) #REQUIRED
	testable (true | false) #REQUIRED
        priority (low | medium | high) #IMPLIED
>

<!--
Example Assertion:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd">
<?xml-stylesheet type="text/xsl" href="https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/xsl/spec_assertions.xsl"?>
<spec>
	<next-available-id>602</next-available-id>
	<previous-id>599</previous-id>
	<technology>JAXRPC</technology>
	<id>JAXRPC 1.0</id>
	<name>Java API for XML-based RPC</name>
	<version>0.7</version>
	<location-names>
	<chapters>
		<chapter id="3" name="Requirements">
			<sections>
				<section id="R01" name="Protocol Bindings"/>
				<section id="R02" name="Transport"/>
				<section id="R03" name="Supported Type Systems"/>
			</sections>
		</chapter>
		<chapter id="4" name="WSDL/XML to Java Mapping"/>
			<sections>
				<section id="1" name="XML Names"/>
				<section id="2.1" name="Simple Types"/>
				<section id="2.2" name="Array"/>
			</sections>
		<chapter id="14" name="Interoperability">
			<sections>
				<section id="1" name="Interoperability Scenario"/>
				<section id="1" name="Interoperability Scenario"/>
				<section id="3.1" name="SOAP based Interoperability"/>
				<section id="3.2" name="SOAP Encoding and XML Schema Support"/>
				<section id="3.3" name="Transport"/>
				<section id="3.4" name="WSDL Requirements"/>
				<section id="3.5" name="Processing of SOAP Headers"/>
				<section id="3.6" name="Mapping of Remote Exceptions"/>
				<section id="3.7" name="Security"/>
				<section id="3.8" name="Transaction"/>
			</sections>
		</chapter>
		<chapter id="15" name="Extensible Type Mapping">
			<sections>
				<section id="2" name="Type Mapping Framework"/>
				<section id="3.1" name="TypeMappingRegistry"/>
			</sections>
		</chapter>
		<chapter id="18" name="XML Schema Support"/>
	</location-names>
	<assertions>
		<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
			<id>441</id>
			<description>The JAX-RPC specification requires the use of one of the following representations for remote call in a SOAP message</description>
			<location chapter="14" section="3.2"/>
			<sub-assertions>
				<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
					<id>441.1</id>
					<description>Encoded representation using the SOAP 1.1 encoding</description>
					<location chapter="14" section="3.2"/>
					<sub-assertions>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.1.1</id>
							<description>The rules and format of serialization for the XML data types are based on the SOAP 1.1 encoding [4].</description>
							<location chapter="14" section="3.2"/>
						</assertion>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.1.2</id>
							<description>An interoperable JAX-RPC implementation is required to support the SOAP 1.1 encoding.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
						<assertion required="false" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.1.3</id>
							<description>Interoperability requirements for any other encodings are outside the scope of the JAX-RPC specification.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
					</sub-assertions>
				</assertion>
				<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
					<id>441.2</id>
					<description>Literal representation</description>
					<location chapter="14" section="3.2"/>
					<sub-assertions>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.2.1</id>
							<description>Each message part in the SOAP body references a concrete schema definition using the element attribute.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
						<assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="true">
							<id>441.2.2</id>
							<description>Each message part in the SOAP body references a concrete schema definition using the type attribute.</description>
							<location chapter="14" section="3.2"/>
						</assertion>
					</sub-assertions>
				</assertion>
			</sub-assertions>
		</assertion>
	</assertions>
</spec>
-->

=== jakartaee/platform-tck/internal/docs/jws/coverage/spec/untestable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd">
<!--

    Copyright (c) 2018, 2020 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<spec>
  <next-available-id>7000</next-available-id>
  <previous-id>0</previous-id>
  <technology>JWS</technology>
  <id>JWS</id>
  <name>Web Services Metadata for the JavaTM Platform</name>
  <version>2.0</version>
  <location>
    <chapters />
    <chapter id="3" name="Server Programming Model">
      <sections>
        <section id="3" name="Web Method" />
        <section id="2" name="Service Endpoint Interface" />
        <section id="1" name="Service Implementation Bean" />
      </sections>
    </chapter>
    <chapter id="5" name="Java Mapping To XML/WSDL">
      <sections>
        <section id="3" name="Web Method Mapping" />
        <section id="2" name="Web Service Class Mapping" />
        <section id="1" name="Service Endpoint Interface" />
      </sections>
    </chapter>
    <chapter id="4" name="Web Services Metadata">
      <sections>
        <section id="3" name="Annotation: jakarta.jws.Oneway" />
        <section id="4.3" name="Example" />
        <section id="6.2" name="Annotation Type Definition" />
        <section id="1.3" name="Example" />
        <section id="3.2" name="Annotation Type Definition" />
        <section id="5.1" name="Description" />
        <section id="2.1" name="Description" />
        <section id="1" name="Annotation: jakarta.jws.WebService" />
        <section id="6" name="Annotation: jakarta.jws.HandlerChain" />
        <section id="1.1" name="Description" />
        <section id="5" name="Annotation: jakarta.jws.WebResult" />
        <section id="2.3" name="Example" />
        <section id="4" name="Annotation: jakarta.jws.WebParam" />
        <section id="1.2" name="Annotation Type Definition" />
        <section id="2.2" name="Annotation Type Definition" />
        <section id="7" name="Annotation: jakarta.jws.SOAPBinding" />
        <section id="2" name="Annotation: jakarta.jws.WebMethod" />
        <section id="7.1" name="Description" />
        <section id="6.1" name="Description" />
        <section id="3.3" name="Example" />
        <section id="7.2" name="Annotation Type Definition" />
        <section id="4.1" name="Description" />
        <section id="5.3" name="Example" />
        <section id="3.1" name="Description" />
        <section id="7.3" name="Example" />
        <section id="4.2" name="Annotation Type Definition" />
        <section id="6.3" name="Example" />
        <section id="5.2" name="Annotation Type Definition" />
      </sections>
    </chapter>
    <chapter id="6" name="SOAP Binding">
      <sections>
        <section id="1.1" name="RPC Operation Style" />
        <section id="1.2.1" name="Document Bare Style" />
        <section id="1.2" name="Document Operation Style" />
        <section id="1" name="Operation Modes" />
      </sections>
    </chapter>
  </location>
  <assertions>
    <assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="false">
      <id>3003</id>
      <description>The implementation MUST NOT define a finalize() method.</description>
      <location chapter="3" section="1" />
    </assertion>
    <assertion required="true" impl-spec="true" defined-by="technology" status="active" testable="false">
      <id>4001</id>
      <description>A JSR-181 processor is REQUIRED to report an error if an operation marked @Oneway has a return value, declares any checked exceptions or has any INOUT or OUT parameters.</description>
      <location chapter="4" section="3.1" />
    </assertion>
    <assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="false">
      <id>4006</id>
      <description>The name attribute of HandlerChain annotation was originally used to associate a JAX-RPC handler in a handler chain with the web service it is declared in.  JAX-WS handlers are associated to web services via elements in the handler chain itself.  In this version, the name is ALWAYS ignored.</description>
      <location chapter="4" section="6.1" />
    </assertion>
    <assertion required="true" impl-spec="true" defined-by="technology" status="active" testable="false">
      <id>4008</id>
      <description>Implementations MUST report an error if the SOAPBinding annotation is placed on a method with a SOAPBinding.style of RPC.</description>
      <location chapter="4" section="7.1" />
    </assertion>
    <assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="false">
      <id>5004</id>
      <description>Each wsdl:port MUST be of the same wsdl:portType, but MAY have different bindings.</description>
      <location chapter="5" section="2" />
    </assertion>
    <assertion required="true" impl-spec="false" defined-by="technology" status="active" testable="false">
      <id>5007</id>
      <description>The wsdl:service MUST contain a distinct wsdl:port for every transport endpoint supported by the service.</description>
      <location chapter="5" section="2" />
    </assertion>
  </assertions>
</spec>

=== jakartaee/platform-tck/internal/docs/jaxws/basicprofile/BasicProfileSpecAssertions.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE spec SYSTEM "https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/dtd/spec_assertions.dtd"[
<!--

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<!ENTITY bp_ch3 SYSTEM "bp_ch3.xml">
<!ENTITY bp_ch4 SYSTEM "bp_ch4.xml">
<!ENTITY bp_ch5 SYSTEM "bp_ch5.xml">
<!ENTITY bp_ch6 SYSTEM "bp_ch6.xml">
]>

<?xml-stylesheet type="text/xsl" href="https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/xsl/spec_assertions.xsl"?>
<spec>
	<next-available-id>10000</next-available-id>
	<previous-id>9999</previous-id>
	<technology>WSIBasicProfile</technology>
	<id>WSI</id>
	<name>Basic Profile</name>
	<version>1.1</version>
	<location-names>
		<chapters>
               <chapter id = "3" name = "Messaging">
                    <sections>
                        <section id = "1" name = "SOAP Envelope"/>
                        <section id = "1.1" name = "SOAP Envelope Structure"/>
                        <section id = "1.2" name = "SOAP Envelope Namespace"/>
                        <section id = "1.3" name = "SOAP Body Namespace Qualification"/>
                        <section id = "1.4" name = "Disallowed Constructs"/>
                        <section id = "1.5" name = "SOAP Trailers"/>
                        <section id = "1.6" name = "SOAP encodingStyle Attribute"/>
                        <section id = "1.7" name = "SOAP mustUnderstand Attribute"/>
                        <section id = "1.8" name = "xsi:type Attributes"/>
                        <section id = "1.9" name = "SOAP1.1 attributes on SOAP1.1 elements"/>
                        <section id = "2" name = "SOAP Processing Model "/>
                        <section id = "2.1" name = "Mandatory Headers"/>
                        <section id = "2.2" name = "Generating mustUnderstand Faults"/>
                        <section id = "2.3" name = "SOAP Fault Processing"/>
                        <section id = "3" name = "SOAP Faults"/>
                        <section id = "3.1" name = "Identifying SOAP Faults"/>
                        <section id = "3.2" name = "SOAP Fault Structure"/>
                        <section id = "3.3" name = "SOAP Fault Namespace Qualification"/>
                        <section id = "3.4" name = "SOAP Fault Extensibility"/>
                        <section id = "3.5" name = "SOAP Fault Language"/>
                        <section id = "3.6" name = "SOAP Custom Fault Codes"/>
                        <section id = "4"   name = "Use of SOAP in HTTP"/>
                        <section id = "4.1" name = "HTTP Protocol Binding"/>
                        <section id = "4.2" name = "HTTP Methods and Extensions"/>
                        <section id = "4.3" name = "SOAPAction HTTP Header"/>
                        <section id = "4.4" name = "HTTP Success Status Codes"/>
                        <section id = "4.5" name = "HTTP Redirect Status Codes"/>
                        <section id = "4.6" name = "HTTP Client Error Status Codes"/>
                        <section id = "4.7" name = "HTTP Server Error Status Codes"/>
                        <section id = "4.8" name = "HTTP Cookies"/>
                    </sections>
               </chapter>
               <chapter id = "4" name = "Service Description">
                    <sections>
                        <section id = "1" name = "Required Description"/>
                        <section id = "2" name = "Document Structure"/>
                        <section id = "2.1" name = "WSDL Schema Definitions"/>
                        <section id = "2.2" name = "WSDL and Schema Import"/>
                        <section id = "2.3" name = "WSDL Import location Attribute Structure"/>
                        <section id = "2.4" name = "WSDL Import location Attribute Semantics"/>
                        <section id = "2.5" name = "Placement of WSDL import Elements"/>
                        <section id = "2.6" name = "XML Version Requirements"/>
                        <section id = "2.7" name = "XML Namespace declarations"/>
                        <section id = "2.8" name = "WSDL and the Unicode BOM"/>
                        <section id = "2.9" name = "Acceptable WSDL Character Encodings"/>
                        <section id = "2.10" name = "Namespace Coercion"/>
                        <section id = "2.11" name = "WSDL documentation Element"/>
                        <section id = "2.12" name = "WSDL Extensions"/>
                        <section id = "3" name = "Types"/>
                        <section id = "3.1" name = "QName References"/>
                        <section id = "3.2" name = "Schema targetNamespace Structure"/>
                        <section id = "3.3" name = "soapenc:Array"/>
                        <section id = "3.4" name = "WSDL and Schema Definition Target Namespaces"/>
                        <section id = "4" name = "Messages"/>
                        <section id = "4.1" name = "Bindings and Parts"/>
                        <section id = "4.2" name = "Bindings and Faults"/>
                        <section id = "4.3" name = "Declaration of part Elements"/>
                        <section id = "5" name = "Port Types"/>
                        <section id = "5.1" name = "Ordering of part Elements"/>
                        <section id = "5.2" name = "Allowed Operations"/>
                        <section id = "5.3" name = "Distinctive Operations"/>
                        <section id = "5.4" name = "parameterOrder Attribute Construction"/>
                        <section id = "5.5" name = "Exclusivity of type and element Attributes"/>
                        <section id = "6" name = "Bindings"/>
                        <section id = "6.1" name = "Use of SOAP Binding"/>
                        <section id = "7" name = "SOAP Binding"/>
                        <section id = "7.1" name = "Specifying the transport Attribute"/>
                        <section id = "7.2" name = "HTTP Transport"/>
                        <section id = "7.3" name = "Consistency of style Attribute"/>
                        <section id = "7.4" name = "Encodings and the use Attribute"/>
                        <section id = "7.5" name = "Multiple Bindings for portType Elements"/>
                        <section id = "7.6" name = "Operation Signatures"/>
                        <section id = "7.7" name = "Multiple Ports on an Endpoint"/>
                        <section id = "7.8" name = "Child Element for Document-Literal Bindings"/>
                        <section id = "7.9" name = "One-Way Operations"/>
                        <section id = "7.10" name = "Namespaces for soapbind Elements"/>
                        <section id = "7.11" name = "Consistency of portType and binding Elements"/>
                        <section id = "7.12" name = "Describing headerfault Elements"/>
                        <section id = "7.13" name = "Enumeration of Faults"/>
                        <section id = "7.14" name = "Type and Name of SOAP Binding Elements"/>
                        <section id = "7.15" name = "name Attribute on Faults"/>
                        <section id = "7.16" name = "Omission of the use Attribute"/>
                        <section id = "7.17" name = "Default for use Attribute"/>
                        <section id = "7.18" name = "Consistency of Envelopes with Descriptions"/>
                        <section id = "7.19" name = "Response Wrappers"/>
                        <section id = "7.20" name = "Part Accessors"/>
                        <section id = "7.21" name = "Namespaces for Children of Part Accessors"/>
                        <section id = "7.22" name = "Required Headers"/>
                        <section id = "7.23" name = "Allowing Undescribed Headers"/>
                        <section id = "7.24" name = "Ordering Headers"/>
                        <section id = "7.25" name = "Describing SOAPAction"/>
                        <section id = "7.26" name = "SOAP Binding Extensions"/>
                        <section id = "8" name = "Use of XML Schema"/>
                    </sections>
               </chapter>
               <chapter id = "5" name = "Service Publication and Discovery">
                    <sections>
                        <section id = "1" name = "bindingTemplates"/>
                        <section id = "2" name = "tModels"/>
                    </sections>
               </chapter>
               <chapter id = "6" name = "Security">
                    <sections>
                        <section id = "1" name = "Use of HTTPS"/>
                    </sections>
               </chapter>
		</chapters>
	</location-names>
	<assertions>
         &bp_ch3;
         &bp_ch4;
         &bp_ch5;
         &bp_ch6;
	</assertions>
</spec>
